import os
import json
import base64
import binascii
from urllib.parse import urlparse

from dotenv import load_dotenv

load_dotenv()

# 认证用户配置文件路径，默认 backend/auth/users.json
_DEFAULT_AUTH_USERS_FILE = os.path.join(os.path.dirname(__file__), "auth", "users.json")
_PRODUCTION_ENVIRONMENTS = {"production", "prod"}


class ProductionConfigurationError(RuntimeError):
    """Raised when a production server is configured with demo-safe defaults."""


def _parse_allowed_origins(raw_origins: str) -> list[str]:
    return [origin.strip() for origin in raw_origins.split(",") if origin.strip()]


def _validate_production_users_file(path: str) -> None:
    if os.path.realpath(path) == os.path.realpath(_DEFAULT_AUTH_USERS_FILE):
        raise ProductionConfigurationError(
            "AUTH_USERS_FILE must point to an externally supplied users file in production; "
            "the bundled demo users file is not allowed."
        )
    if not os.path.isfile(path):
        raise ProductionConfigurationError(
            "AUTH_USERS_FILE must point to a readable users JSON file in production."
        )

    try:
        with open(path, encoding="utf-8") as users_file:
            users = json.load(users_file)
    except (OSError, json.JSONDecodeError) as error:
        raise ProductionConfigurationError(
            "AUTH_USERS_FILE must contain valid JSON in production."
        ) from error

    if not isinstance(users, list) or not users:
        raise ProductionConfigurationError(
            "AUTH_USERS_FILE must contain at least one user in production."
        )
    for user in users:
        if not isinstance(user, dict) or not user.get("username") or not user.get("password_hash"):
            raise ProductionConfigurationError(
                "Production users must have a username and password_hash."
            )
        if "password" in user:
            raise ProductionConfigurationError(
                "Production users must not include plaintext password fields; use password_hash."
            )
        role = user.get("role", "player")
        if role not in ("admin", "player"):
            raise ProductionConfigurationError(
                "Production user role must be 'admin' or 'player'."
            )
        hash_parts = user["password_hash"].split("$")
        if (
            len(hash_parts) != 4
            or hash_parts[0] != "pbkdf2_sha256"
            or not hash_parts[1].isdigit()
            or int(hash_parts[1]) < 1
        ):
            raise ProductionConfigurationError(
                "Production password_hash values must be PBKDF2 hashes generated by auth.passwords."
            )
        try:
            base64.urlsafe_b64decode(hash_parts[2].encode("ascii"))
            base64.urlsafe_b64decode(hash_parts[3].encode("ascii"))
        except (ValueError, binascii.Error) as error:
            raise ProductionConfigurationError(
                "Production password_hash values must be PBKDF2 hashes generated by auth.passwords."
            ) from error


def _validate_production_origins(origins: list[str]) -> None:
    if not origins:
        raise ProductionConfigurationError(
            "ALLOWED_ORIGINS must be explicitly set in production."
        )
    for origin in origins:
        parsed = urlparse(origin)
        if (
            origin == "*"
            or parsed.scheme not in {"http", "https"}
            or not parsed.netloc
            or parsed.path not in {"", "/"}
            or parsed.params
            or parsed.query
            or parsed.fragment
            or parsed.username
            or parsed.password
        ):
            raise ProductionConfigurationError(
                "ALLOWED_ORIGINS must contain explicit HTTP(S) origins only; wildcards and paths are not allowed."
            )

class Config:
    APP_ENV = os.getenv("APP_ENV", "development").lower()
    HOST = os.getenv("HOST", "0.0.0.0")
    PORT = int(os.getenv("PORT", 8765))
    MAX_PLAYERS = 5
    MIN_PLAYERS = 3
    PING_INTERVAL = 20
    PING_TIMEOUT = 20
    ROOM_TTL_SECONDS = float(os.getenv("ROOM_TTL_SECONDS", 300))
    AUTH_USERS_FILE = os.getenv("AUTH_USERS_FILE", _DEFAULT_AUTH_USERS_FILE)
    _RAW_ALLOWED_ORIGINS = os.getenv("ALLOWED_ORIGINS", "")
    ALLOWED_ORIGINS = _parse_allowed_origins(_RAW_ALLOWED_ORIGINS) or None
    MAX_MESSAGES_PER_SECOND = int(os.getenv("MAX_MESSAGES_PER_SECOND", 30))
    ALLOW_LEGACY_JOIN_GAME = os.getenv("ALLOW_LEGACY_JOIN_GAME", "false").lower() in {"1", "true", "yes"}
    E2E_RANDOM_SEED = int(os.environ["E2E_RANDOM_SEED"]) if os.getenv("E2E_RANDOM_SEED") else None

    # Admin API configuration
    ADMIN_HTTP_PORT = int(os.getenv("ADMIN_HTTP_PORT", 8766))
    ADMIN_API_PREFIX = os.getenv("ADMIN_API_PREFIX", "/api/admin")
    ADMIN_SESSION_TTL = int(os.getenv("ADMIN_SESSION_TTL", 3600))

    @classmethod
    def validate_startup_configuration(cls) -> None:
        """Reject insecure defaults before accepting traffic in production."""
        if cls.APP_ENV not in _PRODUCTION_ENVIRONMENTS:
            return

        raw_users_file = os.getenv("AUTH_USERS_FILE", "").strip()
        if not raw_users_file:
            raise ProductionConfigurationError(
                "AUTH_USERS_FILE must be explicitly set in production."
            )
        _validate_production_users_file(raw_users_file)
        _validate_production_origins(_parse_allowed_origins(os.getenv("ALLOWED_ORIGINS", "")))
